//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEvrakTakipUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int raporID { get; set; }
        public Nullable<int> personelID { get; set; }
        public Nullable<int> evrakID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> durumID { get; set; }
        public Nullable<int> yerID { get; set; }
    
        public virtual Durumlar Durumlar { get; set; }
        public virtual Evraklar Evraklar { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Yerler Yerler { get; set; }
    }
}
